from zxcvbn import zxcvbn


print("Password 1")
result = zxcvbn('Summer2026!')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 2")
result = zxcvbn('caramel2')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 3")
result = zxcvbn('England!')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 4")
result = zxcvbn('ABC123')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 5")
result =zxcvbn('1997houseRed')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 6")
result = zxcvbn('aaaaaaaaaa')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 7")
result = zxcvbn('1234567890')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 8")
result = zxcvbn('654dbc')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 9")
result = zxcvbn('FlowerHouse1289@')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")
print()

print("Password 10")
result = zxcvbn('house-flower-pet-boat')
print(result['score'])
print(result['feedback'])
print(f"Guesses: {result['guesses']}")